services:
  - type: web
    name: football-predictor-pro
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: MODEL_GOLS_URL
        value: "https://drive.google.com/uc?id=1XpKUMdD05ZZ70gLDsFaC2wzATm_FCdz7"
      - key: MODEL_WINNER_URL
        value: "https://drive.google.com/uc?id=1b_uaLyGSBjxN8oLJMY0-rlXVbMlFu42R"
